name: Access AWS Secrets

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated to the latest version compatible with Node.js 20

    - name: Assume AWS Role and Retrieve Secret
      uses: aws-actions/configure-aws-credentials@v2 # Assuming v2 is compatible with Node.js 20, check the latest version
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::362356772159:role/sts-lab-2-target
        role-session-name: GitHubActionSession

    - name: Get Secret from AWS Secrets Manager
      run: |
        aws secretsmanager get-secret-value --secret-id flag_sts_lab_2 --region us-east-1
